# Generated by Django 5.2.16 on 2026-08-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_alter_savedreport_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportSchedule',
        ),
    ]
