# Generated by Django 4.2.30 on 2026-07-12 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyProduction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("production_date", models.DateField()),
                ("line_number", models.IntegerField(blank=True, null=True)),
                ("target_quantity", models.IntegerField(blank=True, null=True)),
                ("actual_quantity", models.IntegerField(default=0)),
                ("passed_quantity", models.IntegerField(default=0)),
                ("rejected_quantity", models.IntegerField(default=0)),
                ("efficiency", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("dhu", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("manpower", models.IntegerField(blank=True, null=True)),
                ("working_hours", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("approved", "Approved")], default="active", max_length=20
                    ),
                ),
            ],
            options={
                "ordering": ["-production_date"],
            },
        ),
        migrations.CreateModel(
            name="ProductionPlan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("plan_date", models.DateField()),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("quantity", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
