# Generated by Django 4.2.30 on 2026-07-12 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("merchandising", "0002_initial"),
        ("production", "0001_initial"),
        ("setup", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionplan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productionplan",
            name="factory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="production_plans", to="setup.factory"
            ),
        ),
        migrations.AddField(
            model_name="productionplan",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_plans",
                to="merchandising.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="productionplan",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="dailyproduction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dailyproduction",
            name="factory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="daily_productions", to="setup.factory"
            ),
        ),
        migrations.AddField(
            model_name="dailyproduction",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_productions",
                to="merchandising.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="dailyproduction",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="tenants.tenant"
            ),
        ),
    ]
