# Generated by Django 4.2.30 on 2026-07-12 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("merchandising", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("setup", "0001_initial"),
        ("tenants", "0001_initial"),
        ("commercial", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lcamendment",
            name="approved_by",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="lcamendment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lcamendment",
            name="lc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="amendments", to="commercial.lc"
            ),
        ),
        migrations.AddField(
            model_name="lcamendment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="lc",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lcs",
                to="commercial.bank",
            ),
        ),
        migrations.AddField(
            model_name="lc",
            name="buyer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lcs", to="setup.buyer"),
        ),
        migrations.AddField(
            model_name="lc",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lc",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lcs",
                to="setup.currency",
            ),
        ),
        migrations.AddField(
            model_name="lc",
            name="parent_lc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_lcs",
                to="commercial.lc",
            ),
        ),
        migrations.AddField(
            model_name="lc",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lcs",
                to="merchandising.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="lc",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="bank",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bank",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="tenants.tenant"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lc",
            unique_together={("tenant", "lc_number")},
        ),
        migrations.AlterUniqueTogether(
            name="bank",
            unique_together={("tenant", "code")},
        ),
    ]
