# Generated by Django 5.2.16 on 2026-08-05 10:52

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_salesconfirmation'),
        ('logistics', '0010_shipment_booking_ref_required_date_and_more'),
        ('merchandising', '0022_costing_confirmed_costing_confirmed_at_and_more'),
        ('setup', '0006_vendor_approved_at_vendor_approved_by_and_more'),
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('debit_number', models.CharField(max_length=50, unique=True)),
                ('debit_type', models.CharField(choices=[('fabric_over_tolerance', 'Fabric Over-Tolerance'), ('fabric_shortage', 'Fabric Shortage (Trimmings)'), ('trims_shortage', 'Trims Shortage'), ('final_hit_shortage', 'Final Hit Shortage'), ('other', 'Other')], default='other', max_length=40)),
                ('party_type', models.CharField(choices=[('factory', 'Factory'), ('fabric_supplier', 'Fabric Supplier'), ('trim_supplier', 'Trim Supplier'), ('other', 'Other')], default='factory', max_length=30)),
                ('debited_party', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('shortage_units', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Units short for shortage-type debits (e.g. final hits > 20)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tolerance_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Tolerance the debit was raised against (5% default, 2% Primark/Penney)', max_digits=5)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pro_forma', 'Pro Forma'), ('issued', 'Issued'), ('paid', 'Paid')], default='pro_forma', max_length=20)),
                ('compliance_email', models.CharField(default='compliance@bhms.local', max_length=255)),
                ('compliance_email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_notes', to='setup.currency')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_notes', to='merchandising.purchaseorder')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_notes_raised', to=settings.AUTH_USER_MODEL)),
                ('reconciliation', models.ForeignKey(blank=True, help_text='Final-hit reconciliation that triggered a >20-unit shortage debit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_notes', to='logistics.finalhitreconciliation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Debit Note',
                'verbose_name_plural': 'Debit Notes',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'debit_number')},
            },
        ),
    ]
