# Generated by Django 5.2.16 on 2026-09-02 15:16

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0006_invoiceapproval"),
        ("merchandising", "0033_fitspecification_unique_selected_fit_spec_per_design_sheet"),
        ("setup", "0006_vendor_approved_at_vendor_approved_by_and_more"),
        ("tenants", "0003_alter_tenant_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForwardOrder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("month", models.DateField(help_text="Commitment month (first of month)")),
                ("quantity", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("unit_cost", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, help_text="quantity x unit cost", max_digits=16),
                ),
                (
                    "service_pct",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("3.00"), help_text="Service charge %", max_digits=6
                    ),
                ),
                (
                    "service_charge",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="total cost x service % / 100", max_digits=16
                    ),
                ),
                (
                    "in_hand_units",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Order In-hand tracked quantity", max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("in_production", "In Production"),
                            ("shipped", "Shipped"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="forward_orders", to="setup.buyer"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="forward_orders", to="setup.factory"
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forward_orders",
                        to="merchandising.purchaseorder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Forward Order",
                "verbose_name_plural": "Forward Orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
