# Generated by Django 4.2.30 on 2026-07-12 18:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inspection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[("inline", "Inline"), ("final", "Final"), ("pre shipment", "Pre Shipment")],
                        max_length=50,
                    ),
                ),
                ("inspection_date", models.DateField()),
                ("aql_level", models.DecimalField(decimal_places=1, default=2.5, max_digits=3)),
                ("sample_size", models.IntegerField(blank=True, null=True)),
                ("passed_quantity", models.IntegerField(default=0)),
                ("rejected_quantity", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-inspection_date"],
            },
        ),
        migrations.CreateModel(
            name="InspectionItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("defect_type", models.CharField(max_length=100)),
                ("defect_count", models.IntegerField()),
                (
                    "severity",
                    models.CharField(
                        choices=[("critical", "Critical"), ("major", "Major"), ("minor", "Minor")], max_length=20
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["severity", "defect_type"],
            },
        ),
    ]
