# Generated by Django 4.2.30 on 2026-07-12 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FreightForwarder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("contact_person", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")], default="active", max_length=20
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("shipment_number", models.CharField(max_length=50)),
                ("shipping_line", models.CharField(blank=True, max_length=255)),
                ("vessel_name", models.CharField(blank=True, max_length=255)),
                ("voyage_number", models.CharField(blank=True, max_length=50)),
                ("container_number", models.CharField(blank=True, max_length=50)),
                (
                    "container_size",
                    models.CharField(
                        blank=True,
                        choices=[("20", "20'"), ("40", "40'"), ("40hc", "40' HC"), ("45", "45'")],
                        max_length=20,
                    ),
                ),
                ("port_of_loading", models.CharField(blank=True, max_length=255)),
                ("port_of_discharge", models.CharField(blank=True, max_length=255)),
                ("etd", models.DateField(blank=True, null=True)),
                ("eta", models.DateField(blank=True, null=True)),
                ("atd", models.DateField(blank=True, null=True)),
                ("ata", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("booked", "Booked"),
                            ("document_pending", "Document Pending"),
                            ("document_ready", "Document Ready"),
                            ("container_loaded", "Container Loaded"),
                            ("gate_in", "Gate In"),
                            ("departed", "Departed"),
                            ("in_transit", "In Transit"),
                            ("arrived", "Arrived"),
                            ("cleared", "Cleared"),
                            ("delivered", "Delivered"),
                        ],
                        default="booked",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
