# Generated by Django 4.2.30 on 2026-07-12 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("merchandising", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("commercial", "0002_initial"),
        ("logistics", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="freight_forwarder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipments",
                to="logistics.freightforwarder",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="lc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipments",
                to="commercial.lc",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="shipments", to="merchandising.purchaseorder"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="freightforwarder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="freightforwarder",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="tenants.tenant"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shipment",
            unique_together={("tenant", "shipment_number")},
        ),
        migrations.AlterUniqueTogether(
            name="freightforwarder",
            unique_together={("tenant", "code")},
        ),
    ]
