# Generated by Django 5.2.16 on 2026-07-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_freightforwarder_alter_shipment_freight_forwarder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freightforwarder',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='shipment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='freightforwarder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
