# Generated by Django 5.2.16 on 2026-07-30 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_alter_freightforwarder_options_and_more'),
        ('setup', '0005_risklevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='risk_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='setup.risklevel'),
        ),
    ]
