# Generated by Django 5.2.16 on 2026-08-02 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_shipment_risk_level'),
        ('merchandising', '0016_hit_reparent_to_purchase_order'),
        ('setup', '0006_vendor_approved_at_vendor_approved_by_and_more'),
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingScheduleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('live', 'Live'), ('in_work', 'In Work'), ('delivered', 'Delivered')], default='live', max_length=20)),
                ('cut_qty', models.DecimalField(decimal_places=2, default=0, help_text='Cut quantity filled by planner', max_digits=12)),
                ('garments_ready_qty', models.DecimalField(decimal_places=2, default=0, help_text='Garments ready (fully packed)', max_digits=12)),
                ('ex_factory_date', models.DateField(blank=True, null=True)),
                ('ex_factory_notes', models.TextField(blank=True)),
                ('week_ending', models.DateField(help_text='Week-ending date (Friday)')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('hit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='merchandising.hit')),
                ('risk_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_items', to='setup.risklevel')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='logistics.shipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Booking Schedule Item',
                'verbose_name_plural': 'Booking Schedule Items',
                'ordering': ['week_ending', '-created_at'],
                'unique_together': {('tenant', 'shipment', 'week_ending', 'hit')},
            },
        ),
    ]
