# Generated by Django 5.2.16 on 2026-08-04 18:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_bookingscheduleitem'),
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('docket_number', models.CharField(max_length=50)),
                ('contract_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_raised', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('total_fabric_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unused_fabric_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('sales_notified', models.BooleanField(default=False)),
                ('sales_notified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dockets', to='logistics.shipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Docket',
                'verbose_name_plural': 'Dockets',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'docket_number')},
            },
        ),
    ]
