# Generated by Django 5.2.16 on 2026-08-04 19:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_docket'),
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalHitReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('docket_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantity per the docket / PO', max_digits=12)),
                ('shipped_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantity actually shipped', max_digits=12)),
                ('shortage_units', models.DecimalField(decimal_places=2, default=0, help_text='Shortfall = docket quantity - shipped quantity (minimum 0)', max_digits=12)),
                ('reasons_evident', models.BooleanField(default=False, help_text='Shortage explained by evident reasons (no debit required)')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reconciled', 'Reconciled'), ('debited', 'Debited'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to=settings.AUTH_USER_MODEL)),
                ('schedule_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation', to='logistics.bookingscheduleitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='logistics.shipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Final Hit Reconciliation',
                'verbose_name_plural': 'Final Hit Reconciliations',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'shipment')},
            },
        ),
    ]
