# Generated by Django 5.2.16 on 2026-08-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_finalhitreconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='booking_ref_required_date',
            field=models.DateField(blank=True, help_text='Booking ref deadline: ETA minus 14 days (GC Manual)', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='booking_reference',
            field=models.CharField(blank=True, help_text='Freight booking reference (managed by logistics)', max_length=100),
        ),
    ]
