# Generated by Django 5.2.16 on 2026-09-02 07:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0010_shipment_booking_ref_required_date_and_more"),
        ("setup", "0006_vendor_approved_at_vendor_approved_by_and_more"),
        ("tenants", "0003_alter_tenant_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportRecap",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("s_c_number", models.CharField(blank=True, max_length=60)),
                ("invoice_value", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "item_category",
                    models.CharField(
                        choices=[
                            ("fabric", "Fabric"),
                            ("trims", "Trims"),
                            ("labels", "Labels"),
                            ("accessories", "Accessories"),
                            ("packaging", "Packaging"),
                            ("other", "Other"),
                        ],
                        default="fabric",
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("rolls_bales", models.PositiveIntegerField(blank=True, null=True)),
                ("container", models.CharField(blank=True, max_length=50)),
                ("bl_hawb", models.CharField(blank=True, help_text="Bill of Lading / HAWB number", max_length=60)),
                ("mode", models.CharField(choices=[("sea", "Sea"), ("air", "Air")], default="sea", max_length=10)),
                ("lc_foc", models.CharField(choices=[("lc", "LC"), ("foc", "FOC")], default="lc", max_length=10)),
                ("vessel", models.CharField(blank=True, max_length=100)),
                ("pcd_date", models.DateField(blank=True, help_text="PCD milestone date", null=True)),
                ("etd_date", models.DateField(blank=True, help_text="ETD milestone date", null=True)),
                ("eta_date", models.DateField(blank=True, help_text="ETA milestone date", null=True)),
                ("atb_date", models.DateField(blank=True, help_text="ATB milestone date", null=True)),
                ("unstuffed_date", models.DateField(blank=True, help_text="Unstuffed milestone date", null=True)),
                ("in_house_date", models.DateField(blank=True, help_text="In-house milestone date", null=True)),
                ("agent", models.CharField(blank=True, help_text="Clearing / shipping agent", max_length=120)),
                (
                    "docs_received",
                    models.BooleanField(default=False, help_text="Import documents received (docs workflow flag)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_transit", "In Transit"),
                            ("arrived", "Arrived"),
                            ("unstuffed", "Unstuffed"),
                            ("in_house", "In House"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "factory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_recaps",
                        to="setup.factory",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_recaps",
                        to="setup.vendor",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Recap",
                "verbose_name_plural": "Import Recaps",
                "ordering": ["-created_at"],
            },
        ),
    ]
