# Generated by Django 5.2.16 on 2026-09-02 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0011_importrecap"),
        ("merchandising", "0033_fitspecification_unique_selected_fit_spec_per_design_sheet"),
        ("setup", "0006_vendor_approved_at_vendor_approved_by_and_more"),
        ("tenants", "0003_alter_tenant_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportRecap",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("fob_no", models.CharField(blank=True, help_text="FOB identifier", max_length=60)),
                ("s_c_number", models.CharField(blank=True, max_length=60)),
                ("factory_invoice", models.CharField(blank=True, help_text="Factory invoice number", max_length=80)),
                ("factory_invoice_date", models.DateField(blank=True, null=True)),
                ("customer_invoice", models.CharField(blank=True, help_text="Customer invoice number", max_length=80)),
                ("customer_invoice_date", models.DateField(blank=True, null=True)),
                ("quantity", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("fob_value", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "cmpt_value",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Cut Make Pack Trim value", max_digits=14
                    ),
                ),
                (
                    "cost_value",
                    models.DecimalField(decimal_places=2, default=0, help_text="Landed cost value", max_digits=14),
                ),
                (
                    "service_pct",
                    models.DecimalField(decimal_places=3, default=0, help_text="Service charge %", max_digits=6),
                ),
                ("ex_factory_date", models.DateField(blank=True, null=True)),
                ("mode", models.CharField(choices=[("sea", "Sea"), ("air", "Air")], default="sea", max_length=10)),
                ("hbl", models.CharField(blank=True, help_text="House Bill of Lading", max_length=60)),
                ("on_board_date", models.DateField(blank=True, null=True)),
                ("eta_date", models.DateField(blank=True, null=True)),
                ("container", models.CharField(blank=True, max_length=50)),
                ("bl_number", models.CharField(blank=True, help_text="Bill of Lading number", max_length=60)),
                ("courier", models.CharField(blank=True, max_length=80)),
                ("factory_pay_terms", models.CharField(blank=True, max_length=80)),
                ("factory_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("factory_due_date", models.DateField(blank=True, null=True)),
                ("factory_paid_date", models.DateField(blank=True, null=True)),
                ("customer_pay_terms", models.CharField(blank=True, max_length=80)),
                ("customer_received_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("customer_due_date", models.DateField(blank=True, null=True)),
                ("customer_payment_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "factory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_recaps",
                        to="setup.factory",
                    ),
                ),
                (
                    "forwarder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_recaps",
                        to="logistics.freightforwarder",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_recaps",
                        to="merchandising.purchaseorder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Recap",
                "verbose_name_plural": "Export Recaps",
                "ordering": ["-created_at"],
            },
        ),
    ]
