# Generated by Django 5.2.16 on 2026-09-02 11:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0006_invoiceapproval"),
        ("logistics", "0012_exportrecap"),
        ("merchandising", "0033_fitspecification_unique_selected_fit_spec_per_design_sheet"),
        ("setup", "0006_vendor_approved_at_vendor_approved_by_and_more"),
        ("tenants", "0003_alter_tenant_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierPayment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("payment_ref", models.CharField(help_text="SP log reference", max_length=60)),
                ("invoice_no", models.CharField(blank=True, help_text="Supplier invoice number", max_length=80)),
                ("fn_ref", models.CharField(blank=True, help_text="File number (FN) reference", max_length=60)),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Invoice value allocated against the FN/PO",
                        max_digits=14,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("currency", models.CharField(blank=True, default="USD", max_length=10)),
                ("payment_date", models.DateField(blank=True, help_text="Actual payment date", null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("TT", "TT"), ("LC", "LC"), ("FOC", "FOC"), ("cash", "Cash")],
                        default="TT",
                        max_length=10,
                    ),
                ),
                ("released", models.BooleanField(default=False, help_text="Payment released for settlement")),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_payments",
                        to="commercial.lc",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_payments",
                        to="merchandising.purchaseorder",
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="released_supplier_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_payments",
                        to="setup.vendor",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Payment",
                "verbose_name_plural": "Supplier Payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
