# Generated by Django 5.2.16 on 2026-09-02 13:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0013_supplierpayment"),
        ("merchandising", "0033_fitspecification_unique_selected_fit_spec_per_design_sheet"),
        ("tenants", "0003_alter_tenant_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostReconciliation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "factory_inv_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Factory Invoice (MP) value for the order", max_digits=14
                    ),
                ),
                (
                    "factory_inv_qty",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Invoice quantity for the factory side", max_digits=14
                    ),
                ),
                (
                    "planning_cm_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Planning CM value for the order", max_digits=14
                    ),
                ),
                (
                    "planning_cm_qty",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Order quantity for the planning side", max_digits=14
                    ),
                ),
                (
                    "factory_inv_per_unit",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Factory Invoice value divided by its quantity",
                        max_digits=14,
                    ),
                ),
                (
                    "planning_cm_per_unit",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Planning CM value divided by its quantity",
                        max_digits=14,
                    ),
                ),
                (
                    "saving_loss_per_unit",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Factory Inv per unit - Planning CM per unit (positive = saving, negative = loss)",
                        max_digits=14,
                    ),
                ),
                (
                    "saving_loss_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Saving/Loss per unit x reference quantity",
                        max_digits=14,
                    ),
                ),
                ("is_mismatch", models.BooleanField(default=False, help_text="Factory Inv and Planning CM differ")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reconciled", "Reconciled"),
                            ("disputed", "Disputed"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "costing",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional live costing sheet supplying the planning CM",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_reconciliations",
                        to="merchandising.costing",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "export_recap",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional source export recap supplying the factory invoice",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_reconciliations",
                        to="logistics.exportrecap",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_reconciliations",
                        to="merchandising.purchaseorder",
                    ),
                ),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cost Reconciliation",
                "verbose_name_plural": "Cost Reconciliations",
                "ordering": ["-created_at"],
            },
        ),
    ]
