# Generated by Django 5.2.16 on 2026-09-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0014_costreconciliation"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingscheduleitem",
            name="snapshot_data",
            field=models.JSONField(
                blank=True,
                editable=False,
                help_text="Point-in-time snapshot JSON (cut/garments/ex-factory/status)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bookingscheduleitem",
            name="snapshot_date",
            field=models.DateTimeField(
                blank=True, editable=False, help_text="Timestamp of the last point-in-time snapshot capture", null=True
            ),
        ),
    ]
