# Generated by Django 5.2.16 on 2026-07-12 18:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFABackupCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(help_text='SHA-256 hash of the backup code', max_length=128)),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA Backup Code',
                'verbose_name_plural': 'MFA Backup Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MFASetupLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('regenerated', 'Backup Codes Regenerated'), ('recovery_used', 'Recovery Code Used')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_setup_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA Setup Log',
                'verbose_name_plural': 'MFA Setup Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
