# Generated by Django 5.2.16 on 2026-07-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='tech_pack',
            field=models.FileField(blank=True, null=True, upload_to='tech_packs/'),
        ),
    ]
