# Generated by Django 5.2.16 on 2026-07-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0004_poamendment'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='sketch_back',
            field=models.ImageField(blank=True, null=True, upload_to='sketches/back/'),
        ),
        migrations.AddField(
            model_name='style',
            name='sketch_detail',
            field=models.ImageField(blank=True, null=True, upload_to='sketches/detail/'),
        ),
        migrations.AddField(
            model_name='style',
            name='sketch_front',
            field=models.ImageField(blank=True, null=True, upload_to='sketches/front/'),
        ),
        migrations.AddField(
            model_name='style',
            name='sketch_side',
            field=models.ImageField(blank=True, null=True, upload_to='sketches/side/'),
        ),
    ]
