# Generated by Django 5.2.16 on 2026-07-14 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchandising", "0005_add_style_sketches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileopening",
            name="style_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_openings",
                to="merchandising.styleversion",
            ),
        ),
    ]
