# Generated by Django 5.2.16 on 2026-07-14 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0006_nullable_style_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='costing',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costings', to='merchandising.bom'),
        ),
    ]
