# Generated by Django 5.2.16 on 2026-07-15 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0007_costing_bom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='file_opening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='merchandising.fileopening'),
        ),
    ]
