# Generated by Django 5.2.16 on 2026-07-30 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0009_styleitem'),
        ('setup', '0005_risklevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileopening',
            name='risk_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_openings', to='setup.risklevel'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='risk_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='setup.risklevel'),
        ),
    ]
