# Generated by Django 5.2.16 on 2026-07-30 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchandising", "0011_fileopeningnote"),
        ("setup", "0006_vendor_approved_at_vendor_approved_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bomitem",
            name="actual_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bomitem",
            name="confirmed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bomitem",
            name="delivered_qty",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="bomitem",
            name="eta_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bomitem",
            name="ordered_qty",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="bomitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("TBC", "To Be Confirmed"),
                    ("Ordered", "Ordered"),
                    ("Partial", "Partial Delivery"),
                    ("Completed", "Completed"),
                ],
                default="TBC",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bomitem",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplied_bom_items",
                to="setup.vendor",
            ),
        ),
    ]
