# Generated by Django 5.2.16 on 2026-08-01 17:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0012_bomitem_trim_schedule_fields'),
        ('setup', '0006_vendor_approved_at_vendor_approved_by_and_more'),
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('hit_number', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=100)),
                ('delivery_mode', models.CharField(choices=[('boxed', 'Boxed'), ('hanging', 'Hanging')], default='boxed', max_length=20)),
                ('delivery_type', models.CharField(choices=[('sea', 'Sea'), ('air', 'Air')], default='sea', max_length=20)),
                ('original_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('factory_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hit_overrides', to='setup.factory')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='merchandising.purchaseorderitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'po_item', 'colour')},
            },
        ),
    ]
