# Generated by Django 5.2.16 on 2026-08-01 18:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0013_hit'),
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('fit_stage', models.CharField(choices=[('dev', 'Dev Spec'), ('1st', '1st Fit'), ('2nd', '2nd Fit'), ('3rd', '3rd Fit'), ('pp', 'Pre-Production')], default='dev', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('measurements', models.JSONField(blank=True, default=dict)),
                ('images', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fit_specs', to='merchandising.purchaseorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-is_current', 'created_at'],
                'unique_together': {('purchase_order', 'fit_stage', 'version')},
            },
        ),
    ]
