# Generated by Django 5.2.16 on 2026-08-02

import django.db.models.deletion
from django.db import migrations, models


def backfill_purchase_order(apps, schema_editor):
    Hit = apps.get_model("merchandising", "Hit")
    seen = set()
    for hit in Hit.objects.select_related("po_item").order_by("created_at").iterator():
        if hit.purchase_order_id is None and hit.po_item_id is not None:
            hit.purchase_order_id = hit.po_item.purchase_order_id
        key = (hit.tenant_id, hit.purchase_order_id, hit.colour)
        if key in seen:
            hit.delete()
            continue
        seen.add(key)
        if hit.po_item_id is not None:
            hit.save(update_fields=["purchase_order"])


def reverse_purchase_order(apps, schema_editor):
    Hit = apps.get_model("merchandising", "Hit")
    for hit in Hit.objects.select_related("purchase_order").iterator():
        if hit.po_item_id is None and hit.purchase_order_id is not None:
            first_item = (
                apps.get_model("merchandising", "PurchaseOrderItem")
                .objects.filter(purchase_order_id=hit.purchase_order_id)
                .first()
            )
            if first_item is not None:
                hit.po_item_id = first_item.id
                hit.save(update_fields=["po_item"])


class Migration(migrations.Migration):

    dependencies = [
        ("merchandising", "0015_jobrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="hit",
            name="purchase_order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hits",
                to="merchandising.purchaseorder",
            ),
        ),
        migrations.RunPython(backfill_purchase_order, reverse_purchase_order),
        migrations.AlterUniqueTogether(
            name="hit",
            unique_together={("tenant", "purchase_order", "colour")},
        ),
        migrations.RemoveField(
            model_name="hit",
            name="po_item",
        ),
        migrations.AlterField(
            model_name="hit",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hits",
                to="merchandising.purchaseorder",
            ),
        ),
    ]
