# Generated by Django 5.2.16 on 2026-08-03 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0016_hit_reparent_to_purchase_order'),
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('image', models.ImageField(upload_to='design_images/')),
                ('role', models.CharField(choices=[('main', 'Main'), ('range', 'Range'), ('colourway', 'Colourway'), ('detail', 'Detail')], default='main', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('colourway', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_main', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_images', to='merchandising.style')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['sort_order', '-is_main', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('style', 'is_main'), name='unique_main_design_image_per_style')],
            },
        ),
    ]
