# Generated by Django 5.2.16 on 2026-08-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0017_designimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileopening',
            name='is_quick_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fileopening',
            name='quick_lead_agreed_by',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
