# Generated by Django 5.2.16 on 2026-08-03 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0018_fileopening_is_quick_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileopening',
            name='is_repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fileopening',
            name='original_fn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repeats', to='merchandising.fileopening'),
        ),
        migrations.AddField(
            model_name='fileopening',
            name='repeat_approved_by',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
