# Generated by Django 5.2.16 on 2026-08-03 18:14

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0019_fileopening_is_repeat_fileopening_original_fn_and_more'),
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fileopening',
            name='allocated_meters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fileopening',
            name='is_stock_fabric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fileopening',
            name='stock_fabric_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fileopening',
            name='stock_photo',
            field=models.ImageField(blank=True, null=True, upload_to='stock_fabric/'),
        ),
        migrations.AddField(
            model_name='fileopening',
            name='total_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='StockFabricAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('meters', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocated_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('allocated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_allocations_in', to='merchandising.fileopening')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_allocations', to='merchandising.fileopening')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Stock Fabric Allocation',
                'verbose_name_plural': 'Stock Fabric Allocations',
                'ordering': ['-created_at'],
            },
        ),
    ]
