# Generated by Django 5.2.16 on 2026-08-05 06:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0020_fileopening_allocated_meters_and_more'),
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='costing',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GBP per 1 USD; used to convert USD costings into GBP for landed orders', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='costing',
            name='is_live',
            field=models.BooleanField(default=True, help_text='Ticked live costing sheet for this order'),
        ),
        migrations.AddField(
            model_name='costing',
            name='sheet_type',
            field=models.CharField(choices=[('sl', 'Sri Lanka'), ('vn', 'Vietnam'), ('bd', 'Bangladesh'), ('cn', 'China'), ('other', 'Other')], default='sl', max_length=10),
        ),
        migrations.CreateModel(
            name='CostingLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category', models.CharField(choices=[('fabric', 'Fabric'), ('trim', 'Trims'), ('label', 'Labels'), ('making', 'Making (CM)'), ('overhead', 'Overheads'), ('packaging', 'Packaging'), ('freight', 'Transport / Freight'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('consumption', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('is_additional', models.BooleanField(default=False)),
                ('original_description', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_costing_lines', to=settings.AUTH_USER_MODEL)),
                ('costing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='merchandising.costing')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
