# Generated by Django 5.2.16 on 2026-08-05 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0021_costing_exchange_rate_costing_is_live_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='costing',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Ticked only once the costing is confirmed with the customer'),
        ),
        migrations.AddField(
            model_name='costing',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='costing',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_costings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costing',
            name='is_patterned',
            field=models.BooleanField(default=False, help_text='Patterned fabric requires additional options for an accurate costing'),
        ),
        migrations.AddField(
            model_name='costing',
            name='is_single_size',
            field=models.BooleanField(default=False, help_text='Single-size costing; a watermark is shown over the image as it must not be used for production purposes'),
        ),
        migrations.AddField(
            model_name='costing',
            name='notes',
            field=models.TextField(blank=True, help_text='Free-text notes box on the design costing'),
        ),
        migrations.AddField(
            model_name='costing',
            name='patterned_fabric_options',
            field=models.JSONField(blank=True, default=list, help_text='Subset of the 4 pattern options for patterned fabric'),
        ),
        migrations.AddField(
            model_name='costing',
            name='size_ratio',
            field=models.JSONField(blank=True, default=list, help_text='List of {size, ratio} entries stating the sizes and ratio for the costing'),
        ),
        migrations.AddField(
            model_name='costingline',
            name='size_width',
            field=models.CharField(blank=True, help_text='Size / width column for costing-schedule accuracy', max_length=50),
        ),
    ]
