# Generated by Django 5.2.16 on 2026-08-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0023_hit_colour_colorcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costing',
            name='sheet_type',
            field=models.CharField(choices=[('sl', 'Sri Lanka'), ('vn', 'Vietnam'), ('bd', 'Bangladesh'), ('cn', 'China'), ('other', 'Other')], default='bd', max_length=10),
        ),
    ]
