# Generated by Django 5.2.17 on 2026-08-10 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0024_alter_costing_sheet_type'),
        ('tenants', '0003_alter_tenant_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleTechPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('techpack_number', models.CharField(max_length=50)),
                ('source_pdf', models.FileField(blank=True, upload_to='tech_packs/source/')),
                ('excel_file', models.FileField(blank=True, upload_to='tech_packs/excel/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('extracted', 'Extracted'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('block', models.CharField(blank=True, max_length=100)),
                ('based_on', models.CharField(blank=True, max_length=100)),
                ('customer', models.CharField(blank=True, max_length=100)),
                ('style_number', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('designer', models.CharField(blank=True, max_length=100)),
                ('pattern_cutter', models.CharField(blank=True, max_length=100)),
                ('issuer', models.CharField(blank=True, max_length=100)),
                ('cloth_code', models.CharField(blank=True, max_length=255)),
                ('length', models.CharField(blank=True, max_length=50)),
                ('sketch', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_packs', to='merchandising.style')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'techpack_number')},
            },
        ),
    ]
