# Generated by Django 5.2.17 on 2026-08-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0026_bomitem_techpack_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomitem',
            name='colour',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='match',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='width_size',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
