# Generated by Django 5.2.17 on 2026-08-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchandising", "0027_bomitem_techpack_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="styletechpack",
            name="notes_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="styletechpack",
            name="notes_initials",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="styletechpack",
            name="other_images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="styletechpack",
            name="sketch_image",
            field=models.ImageField(blank=True, null=True, upload_to="tech_packs/sketches/"),
        ),
    ]
