# Generated by Django 5.2.17 on 2026-08-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchandising", "0029_design_sheet_fit_spec_job_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="styletechpack",
            name="sketch_thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="tech_packs/sketches/thumbs/"),
        ),
    ]
