# Generated by Django 5.2.17 on 2026-08-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchandising", "0030_styletechpack_sketch_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="designsheet",
            name="sketch_annotations",
            field=models.JSONField(
                blank=True, default=list, help_text="List of {id, x, y, text} sketch annotations (percentages 0-100)"
            ),
        ),
    ]
