# Generated by Django 5.2.17 on 2026-08-31 05:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchandising", "0032_designsheet_backfill_data"),
        ("tenants", "0003_alter_tenant_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="fitspecification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_selected", True)),
                fields=("tenant", "design_sheet"),
                name="unique_selected_fit_spec_per_design_sheet",
            ),
        ),
    ]
