# Generated by Django 5.2.16 on 2026-09-04 15:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchandising", "0033_fitspecification_unique_selected_fit_spec_per_design_sheet"),
        ("tenants", "0003_alter_tenant_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignCosting",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "sheet_type",
                    models.CharField(
                        choices=[
                            ("sl", "Sri Lanka"),
                            ("vn", "Vietnam"),
                            ("bd", "Bangladesh"),
                            ("cn", "China"),
                            ("other", "Other"),
                        ],
                        default="bd",
                        max_length=10,
                    ),
                ),
                ("is_live", models.BooleanField(default=True, help_text="Ticked live design costing for this style")),
                ("target_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("fabric_cost", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("trim_cost", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("cm_cost", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("overhead_cost", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("total_cost", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("margin", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("is_single_size", models.BooleanField(default=False)),
                ("size_ratio", models.JSONField(blank=True, default=list)),
                ("is_patterned", models.BooleanField(default=False)),
                ("patterned_fabric_options", models.JSONField(blank=True, default=list)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_design_costings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_costings",
                        to="merchandising.style",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "unique_together": {("tenant", "style", "version")},
            },
        ),
        migrations.CreateModel(
            name="DesignCostingLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fabric", "Fabric"),
                            ("trim", "Trims"),
                            ("label", "Labels"),
                            ("making", "Making (CM)"),
                            ("overhead", "Overheads"),
                            ("packaging", "Packaging"),
                            ("freight", "Transport / Freight"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("unit_price", models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ("consumption", models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ("size_width", models.CharField(blank=True, max_length=50)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "costing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="merchandising.designcosting",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
    ]
