# Generated by Django 5.2.16 on 2026-09-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchandising", "0034_designcosting_designcostingline"),
    ]

    operations = [
        migrations.AddField(
            model_name="designsheet",
            name="layout_order",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ordered list of content-block keys rendered on the design-sheet page",
            ),
        ),
    ]
