# Generated by Django 5.2.16 on 2026-09-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchandising", "0035_designsheet_layout_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="styletechpack",
            name="contains",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="styletechpack",
            name="pattern_request_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="styletechpack",
            name="risk_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="styletechpack",
            name="style_type",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
