# Generated by Django 5.2.16 on 2026-09-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchandising", "0036_styletechpack_contains_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="styletechpack",
            name="relationship",
            field=models.CharField(
                blank=True,
                choices=[("based_on", "Based on"), ("na", "NA"), ("recut", "Recut"), ("new", "New")],
                default="new",
                help_text="Relationship of this design to a base (Based on / NA / Recut / New)",
                max_length=20,
            ),
        ),
    ]
