# Generated by Django 5.2.16 on 2026-09-06 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchandising", "0037_design_relationship"),
        ("setup", "0006_vendor_approved_at_vendor_approved_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="styletechpack",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tech_packs",
                to="setup.buyer",
            ),
        ),
        migrations.AddField(
            model_name="styletechpack",
            name="product_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tech_packs",
                to="setup.producttype",
            ),
        ),
        migrations.AddField(
            model_name="styletechpack",
            name="style_code",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
