# Generated by Django 5.2.16 on 2026-09-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchandising", "0038_design_init_typed_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="styletechpack",
            name="style_type",
        ),
    ]
