# Generated by Django 5.2.17 on 2026-09-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0039_remove_styletechpack_style_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='based_on',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='style',
            name='block',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='style',
            name='cloth_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='style',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='style',
            name='design_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='style',
            name='designer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='style',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='issuer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='style',
            name='length',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='style',
            name='pattern_cutter',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='style',
            name='pattern_request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='relationship',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('based_on', 'Based on'), ('na', 'NA'), ('recut', 'Recut')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='style',
            name='risk_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='size',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsheet',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('rejected', 'Rejected'), ('closed', 'Closed'), ('production', 'Production'), ('archived', 'Archived')], default='new', max_length=20),
        ),
    ]
