# Generated by Django 5.2.17 on 2026-09-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchandising", "0041_buyer_merge"),
    ]

    operations = [
        migrations.AddField(
            model_name="designimage",
            name="annotations",
            field=models.JSONField(
                blank=True, default=list, help_text="Per-image annotation list: [{id, x, y, text}]."
            ),
        ),
    ]
