# Generated by Django 5.2.17 on 2026-09-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchandising", "0042_designimage_annotations"),
    ]

    operations = [
        migrations.AddField(
            model_name="designcosting",
            name="customer_discount_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Customer discount % applied on the selling price (reference price ladder).",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="designcosting",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="GBP per 1 USD (dollar rate); converts total cost into GBP landed cost.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="designcosting",
            name="origin_overhead_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="BD/VN/CN origin overhead % applied on the per-piece total cost.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="designcosting",
            name="selling_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Selling price for the per-piece ladder (reference 'Selling Price').",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="designcosting",
            name="uk_overhead_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="UK overhead % applied on the per-piece total cost.",
                max_digits=5,
            ),
        ),
    ]
