# Generated by Django 5.2.17 on 2026-09-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchandising", "0043_designcosting_customer_discount_pct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="costing",
            name="customer_discount_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Customer discount % snapshot from the design costing.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="costing",
            name="origin_overhead_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Origin overhead % snapshot from the design costing.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="costing",
            name="po_base_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="PO base cost = per-piece base_cost × po_quantity.",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="costing",
            name="po_margin_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="PO margin = per-piece margin_amount × po_quantity.",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="costing",
            name="po_quantity",
            field=models.IntegerField(default=0, help_text="Frozen PO quantity snapshot at prepare time."),
        ),
        migrations.AddField(
            model_name="costing",
            name="po_total_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="PO total cost = per-piece total_cost × po_quantity.",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="costing",
            name="selling_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Selling price snapshot from the design costing.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="costing",
            name="uk_overhead_pct",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="UK overhead % snapshot from the design costing.", max_digits=5
            ),
        ),
    ]
