# Generated by Django 5.2.16 on 2026-07-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_department_description_department_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
