# Generated by Django 5.2.16 on 2026-08-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='currency',
            field=models.CharField(default='BDT', max_length=3),
        ),
    ]
