# Generated by Django 5.2.16 on 2026-07-30 19:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fabric", "0001_initial"),
        ("tenants", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FabricOrder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order_number", models.CharField(max_length=50)),
                ("quantity_meters", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("total_price", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("lab_dip_pending", "Lab Dip Pending"),
                            ("lab_dip_approved", "Lab Dip Approved"),
                            ("bulk_approved", "Bulk Approved"),
                            ("in_production", "In Production"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("lab_dip_required_date", models.DateField(blank=True, null=True)),
                ("lab_dip_actual_date", models.DateField(blank=True, null=True)),
                ("lab_dip_approval_date", models.DateField(blank=True, null=True)),
                ("lab_dip_notes", models.TextField(blank=True)),
                ("bulk_approved_date", models.DateField(blank=True, null=True)),
                ("onboard_date", models.DateField(blank=True, null=True)),
                ("eta_date", models.DateField(blank=True, null=True)),
                ("clearance_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "bulk_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_approved_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fabric_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fabric_orders",
                        to="fabric.fabriccategory",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fabric_orders",
                        to="fabric.fabricsupplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fabric Order",
                "verbose_name_plural": "Fabric Orders",
                "ordering": ["-created_at"],
                "unique_together": {("tenant", "order_number")},
            },
        ),
    ]
