# Generated by Django 5.2.16 on 2026-08-03 18:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0002_fabric_order'),
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricTolerance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('customer_type', models.CharField(choices=[('primark', "Primark/Penney's"), ('other', 'Other Customers'), ('fur', 'All Fur Orders')], max_length=20)),
                ('qty_from', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qty_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tolerance_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Fabric Tolerance',
                'verbose_name_plural': 'Fabric Tolerances',
                'ordering': ['customer_type', 'qty_from'],
                'unique_together': {('tenant', 'customer_type', 'qty_from')},
            },
        ),
    ]
