# Generated by Django 5.2.16 on 2026-08-03 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0003_fabrictolerance'),
        ('setup', '0006_vendor_approved_at_vendor_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricorder',
            name='date_owners',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fabricorder',
            name='risk_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabric_orders', to='setup.risklevel'),
        ),
        migrations.AddField(
            model_name='fabricorder',
            name='risk_notes',
            field=models.TextField(blank=True),
        ),
    ]
