# Generated by Django 5.2.16 on 2026-08-04 16:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0004_fabricorder_date_owners_fabricorder_risk_level_and_more'),
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricScheduleHandoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('date_key', models.CharField(max_length=30)),
                ('from_role', models.CharField(max_length=30)),
                ('to_role', models.CharField(max_length=30)),
                ('trigger', models.CharField(choices=[('dip_approved', 'Lab Dip Approved'), ('bulk_approved', 'Bulk Approved'), ('manual', 'Manual Handoff')], default='manual', max_length=20)),
                ('handed_off_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('handed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_handoffs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_handoffs', to='fabric.fabricorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Fabric Schedule Handoff',
                'verbose_name_plural': 'Fabric Schedule Handoffs',
                'ordering': ['handed_off_at', '-id'],
            },
        ),
    ]
