# Generated by Django 5.2.16 on 2026-08-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0006_fabricutilization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FabricInventory',
        ),
    ]
