# Generated by Django 5.2.16 on 2026-09-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fabric", "0007_delete_fabricinventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="fabricorder",
            name="actual_arrival_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fabricorder",
            name="bulk_approved_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fabricorder",
            name="paperwork_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fabricorder",
            name="strike_off_actual_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fabricorder",
            name="strike_off_approval_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fabricorder",
            name="strike_off_required_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
